[package]
name = "__darwin-libproc"
version = "0.1.0"
license = "MIT"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
darwin-libproc = "0.2.0"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
